version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: user-api-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: user-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data: